### ISSUE TITLE
"TwitterApi is not a constructor" error

### ISSUE THREAD

**Issue by metehus** [PLhery/node-twitter-api#17]
I'm using twitter-api-v2 0.3.0 with this code:

```js
const TwitterApi = require('twitter-api-v2')

const twitter = new TwitterApi(process.env.TWT_TOKEN)
```

But i get this problem when trying to execute:

```
const twitter = new TwitterApi(process.env.TWT_TOKEN)
                ^

TypeError: TwitterApi is not a constructor
    at Object.<anonymous> (/mnt/d/Projects/bots/twt/src/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

If there's anything more needed for that issue, just ask me!

**Comment by PLhery** [comment]
Currently the TwitterApi object is exported as "default"  so that we can write` import TwitterApi from 'twitter-api-v2';`

Therefore you could do something like this:

```js
const TwApiModule = require('twitter-api-v2')
const TwitterApi = TwApiModule.default;
new TwitterApi(xxx);
```

However, now I think I should also export it as TwitterApi so that we can do something like this instead, I'll work on it :)

```js
const { TwitterApi } = require('twitter-api-v2');
new TwitterApi(xxx);
```

**Comment by metehus** [comment]
That would be awesome. Thanks!

**Comment by alkihis** [comment]
Fixed in https://github.com/PLhery/node-twitter-api/commit/5bc32a72ff21068454e46f31931e83164ece4b69 ; awaiting next npm release to close issue :)

**Comment by PLhery** [comment]
Published :) https://github.com/PLhery/node-twitter-api/releases/tag/0.4.0
